version: "3.3"
services:
  py:
    image: python
    volumes: 
      - ./:/app/
    working_dir: /app
    command:
      bash -c "pip install -r req.txt -f https://download.pytorch.org/whl/torch_stable.html &&
      gunicorn -k uvicorn.workers.UvicornWorker --log-level trace main:app -b :80"
    ports:
      - 8003:80